name: CI Checks

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  building:
    name: Building
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      matrix:
        rust: [nightly] # using trap_unreachable = no, which is nightly-only rn
        include:
          - rust: nightly
            experimental: true
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          target: thumbv6m-none-eabi
      - run: cargo install flip-link
      - run: cargo build --all
      - run: cargo build --all --release
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
          target: thumbv6m-none-eabi
      - run: cargo clippy --all-features -- --deny=warnings
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
          target: thumbv6m-none-eabi
      - run: cargo fmt -- --check
